import type { GuidePrefaceDef, GuideSectionDef } from './types'

export const enGuideEnterLines = [
  'If you would enter the mist,',
  'six volumes below.',
  'If you would stay on shore,',
  'shared view is enough.',
] as const

export const enGuidePreface: GuidePrefaceDef = {
  illustrationId: '01-shore-near',
  frame: ['Shared View', 'Each paused in place.'],
  whisper: ['The shore is not far.', 'The mist not yet deep.'],
  note: [
    'What follows are vignettes—',
    'each with one person, each paused in place.',
    'They need not be read straight through.',
    'To stop on one page is enough.',
  ],
}

export const enGuideSections: readonly GuideSectionDef[] = [
  {
    id: 'tongguan',
    title: 'Shared View',
    illustrationId: 'v-tongguan',
    into: ['In a life, there will always be questions no one can answer.'],
    afterglow: ['Those questions remain.', 'Only the one who asked', 'has already walked on.'],
    lines: [
      'Some stop at parting.',
      'Some stop at responsibility.',
      'Some stop at loss.',
      'Some stop at farewell.',
      'Some stop at change.',
      'Some stop at the future.',
      'No one can answer those questions for you.',
      'Only years later, when you look back,',
      'perhaps you will see the person you were has quietly walked away.',
    ],
  },
  {
    id: 'liubai',
    title: 'White Space',
    illustrationId: 'v-liubai',
    into: ['She was twenty-five.', 'Day twenty-three after the breakup.'],
    bridge: ['Many years later.'],
    afterglow: ['The chat window is gone now.', 'She did not go looking for it.'],
    lines: [
      'That year.',
      'Friends told her to let go.',
      'She tried many things.',
      'Travel.',
      'Exercise.',
      'Deleting photos.',
      'Changing jobs.',
      'One day.',
      'She emptied the photo album.',
      'The chat window she kept.',
      'pause',
      'Many years later.',
      'While moving.',
      'She stopped a long while at the bottom of a box.',
      'Brushed the dust away gently.',
      'Put it back on the shelf.',
      'Went on packing.',
      'Later.',
      'The chat window was gone.',
      'She did not wonder.',
      'When it had been deleted.',
    ],
  },
  {
    id: 'changye',
    title: 'Long Night',
    illustrationId: 'v-changye',
    into: ['The first month after the child was born.', 'Only he could not sleep.'],
    bridge: ['Many years later.'],
    afterglow: ['The habit of three bowls of rice,', 'lasted longer than that night.'],
    lines: [
      'That year.',
      'He was thirty-one.',
      'Everyone said:',
      '"Congratulations."',
      'Midnight.',
      'The child cried.',
      'He held the child and stood by the window.',
      'Stood there until dawn.',
      'pause',
      'Many years later.',
      'The child left for college.',
      'Back from seeing him off.',
      'He came home.',
      'Still set out three bowls of rice by habit.',
      'When he set down his chopsticks.',
      'Only then noticed two people left at home.',
      'That night.',
      'He opened a drawer.',
      'Paused a moment.',
      'Closed it gently again.',
    ],
  },
  {
    id: 'menpai',
    title: 'Nameplate',
    illustrationId: 'v-menpai',
    into: ['The day the office was emptied.', 'The last thing she took was the nameplate.'],
    bridge: ['Five years later.'],
    afterglow: ['The old nameplate still in the drawer.', 'On the new desk, no nameplate.'],
    lines: [
      'That year.',
      'She was forty-two.',
      'The startup failed.',
      'Not the computers.',
      'The sign by the door with her name on it.',
      'Later.',
      'Someone asked her:',
      '"What do you do now?"',
      'She paused.',
      'Smiled and changed the subject.',
      'pause',
      'Five years later.',
      'She moved into a new office.',
      'Very small.',
      'No nameplate on the desk.',
      'In the drawer.',
      'The old nameplate was still there.',
      'She glanced at it.',
      'Closed the drawer gently.',
      'Did not take it out.',
    ],
  },
  {
    id: 'huisheng',
    title: 'Echo',
    illustrationId: 'v-huisheng',
    into: ['After her mother passed.', 'She never changed her phone.'],
    bridge: ['A few years later.'],
    afterglow: ['"Come home for dinner."', 'She never heard it again.', 'Yet she often thought of it at dusk.'],
    lines: [
      'That year.',
      'She was thirty-six.',
      'Because it still held one last voice message.',
      'Only one line.',
      '"Come home for dinner."',
      'Later.',
      'The system warned storage was full.',
      'She deleted many things.',
      'Except that message.',
      'She kept it.',
      'pause',
      'A few years later.',
      'She got a new phone.',
      'Most of her data moved over.',
      'Only that message.',
      'Did not.',
      'That evening.',
      'She sat by the window.',
      'Did not speak for a long time.',
      'When she rose.',
      'She closed the drawer gently.',
    ],
  },
  {
    id: 'qingchen',
    title: 'Early Morning',
    illustrationId: 'v-qingchen',
    into: ['His first year of retirement.', 'He still woke at six.'],
    bridge: ['Three years later.'],
    afterglow: ['The bus drove away.', 'He stood at the door a while longer.'],
    lines: [
      'That year.',
      'He was sixty-three.',
      'Washed up.',
      'Changed clothes.',
      'Walked to the door.',
      'Then took his shoes off again.',
      'One day.',
      'The bus came.',
      'He stood there.',
      'Did not board.',
      'The bus moved slowly away.',
      'He did not move.',
      'pause',
      'Three years later.',
      'He still woke at six.',
      'Only the first thing he did.',
      'Was water the flowers on the balcony.',
      'When the flowers bloomed.',
      'He stood there.',
      'Looked a long while.',
      'Then picked up the watering can.',
      'Moved on to the next pot.',
    ],
  },
  {
    id: 'yuanxing',
    title: 'Long Journey',
    illustrationId: 'v-yuanxing',
    into: ['The year he turned fifty-four.', 'The first time he kept that page.'],
    bridge: ['Many years later.'],
    afterglow: ['The pages have yellowed.', 'He went out the door.'],
    lines: [
      'Not for himself.',
      'pause',
      'Many years later.',
      'Sorting the study.',
      'Papers in the corner had yellowed.',
      'He opened the first page again.',
      'Stayed there a long while.',
      'Wind rose outside the window.',
      'He closed it gently.',
      'Put it in the bag he carried.',
      'Went out the door.',
    ],
  },
  {
    id: 'liujuan',
    title: 'Six Volumes',
    illustrationId: 'v-liujuan',
    into: ['Shared view read.', 'If you would go deeper—'],
    afterglow: ['To here.', 'If you would go inward,', 'six volumes on the shore.'],
    lines: [
      'Life does not stay on the same page.',
      'Some walk fast.',
      'Some walk slow.',
      'Some never find an answer.',
      'Some later forget the question.',
      'Many years later.',
      'Opening the page once left behind.',
      'What remains',
      'is not always the answer.',
      'More often,',
      'it is the trace of the road walked.',
      'A person cannot be known in one volume.',
      'A heart cannot be seen from one face.',
      'A life cannot be fixed in one moment.',
      'So six volumes, to view life together.',
      'Six volumes are not six personalities.',
      'Nor six judgments.',
      'Only six directions from which to view a life.',
      'Mindscape, to mirror the self.',
      'Heart Mirror, to mirror emotion.',
      'Clear Thought, to mirror cognition.',
      'Bond Book, to mirror relationship.',
      'Flow Balance, to mirror change.',
      'Toward Light, to mirror direction.',
      'Six volumes, viewed together.',
      'Not to define.',
      'Only to leave a trace.',
    ],
  },
]
